from tkinter import *
root=Tk()
root.title('My notepad')
root.geometry('400x700')
menubar=Menu(root)
root.config(menu=menubar)
filemenu=Menu(menubar)
editmenu=Menu(menubar)
viewmenu=Menu(menubar)
menubar.add_cascade(label="File",menu=filemenu,underline=0)
menubar.add_cascade(label="Edit",menu=editmenu,underline=0)
menubar.add_cascade(label="View",menu=viewmenu,underline=0)
submenu=Menu(viewmenu,tearoff=0)
submenu.add_command(label='zoom in')
submenu.add_command(label='zoom out')
submenu.add_command(label='restore default zoom')
filemenu.add_command(label='New')
filemenu.add_command(label='New window')
filemenu.add_command(label='Open')
filemenu.add_command(label='Save')
filemenu.add_command(label='Save as')
filemenu.add_command(label='Page setup')
filemenu.add_command(label='Print')
filemenu.add_command(label='Exit')
#-------------------------------------
editmenu.add_command(label='Undo')
editmenu.add_command(label='Cut')
editmenu.add_command(label='Copy')
editmenu.add_command(label='Paste')
editmenu.add_command(label='Delete')
editmenu.add_command(label='Find')
editmenu.add_command(label='Find next')
editmenu.add_command(label='Find previous')
editmenu.add_command(label='Replace')
editmenu.add_command(label='Go to')
editmenu.add_command(label='Select all')
editmenu.add_command(label='Time/Date')
editmenu.add_command(label='Font')
#-----------------------------------------
viewmenu.add_cascade(label='Zoom',menu=submenu)
viewmenu.add_command(label='Status bar')
viewmenu.add_command(label='Word wrap')
root.mainloop()
